<?php
// Automatically Generated by TestLink Installer - Wed, 30 May 18 10:58:36 +0200
define('DB_TYPE', 'mysql');
define('DB_USER', 'testlinkuser');
define('DB_PASS', 'Hendrix-1991');
define('DB_HOST', 'localhost');
define('DB_NAME', 'testlink');
define('DB_TABLE_PREFIX', '');
